# Generated by Django 6.1.1 on 2026-09-27 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_id', models.CharField(max_length=20, unique=True)),
                ('modality', models.CharField(choices=[('XR', 'X-ray'), ('CT', 'CT'), ('MR', 'MRI')], max_length=2)),
                ('body_part', models.CharField(max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('critical', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='triage.study')),
            ],
        ),
    ]
